// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner.proto

package com.rcosteira.rabbitmq_protobufs_android;

public final class PartnerProto {
  private PartnerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PartnerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:partnerpackage.Partner)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     * becomes updatedAt
     * </pre>
     *
     * <code>uint64 updated_at = 2;</code>
     */
    long getUpdatedAt();

    /**
     * <pre>
     * becomes createdAt
     * </pre>
     *
     * <code>uint64 created_at = 3;</code>
     */
    long getCreatedAt();

    /**
     * <pre>
     * becomes webSite
     * </pre>
     *
     * <code>string web_site = 4;</code>
     */
    java.lang.String getWebSite();
    /**
     * <pre>
     * becomes webSite
     * </pre>
     *
     * <code>string web_site = 4;</code>
     */
    com.google.protobuf.ByteString
        getWebSiteBytes();

    /**
     * <code>string description = 5;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 5;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string name = 6;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 6;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 version = 7;</code>
     */
    int getVersion();

    /**
     * <code>string picture = 8;</code>
     */
    java.lang.String getPicture();
    /**
     * <code>string picture = 8;</code>
     */
    com.google.protobuf.ByteString
        getPictureBytes();
  }
  /**
   * Protobuf type {@code partnerpackage.Partner}
   */
  public  static final class Partner extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:partnerpackage.Partner)
      PartnerOrBuilder {
    // Use Partner.newBuilder() to construct.
    private Partner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Partner() {
      id_ = "";
      updatedAt_ = 0L;
      createdAt_ = 0L;
      webSite_ = "";
      description_ = "";
      name_ = "";
      version_ = 0;
      picture_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Partner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              updatedAt_ = input.readUInt64();
              break;
            }
            case 24: {

              createdAt_ = input.readUInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              webSite_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 56: {

              version_ = input.readUInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              picture_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rcosteira.rabbitmq_protobufs_android.PartnerProto.internal_static_partnerpackage_Partner_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rcosteira.rabbitmq_protobufs_android.PartnerProto.internal_static_partnerpackage_Partner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner.class, com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 2;
    private long updatedAt_;
    /**
     * <pre>
     * becomes updatedAt
     * </pre>
     *
     * <code>uint64 updated_at = 2;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }

    public static final int CREATED_AT_FIELD_NUMBER = 3;
    private long createdAt_;
    /**
     * <pre>
     * becomes createdAt
     * </pre>
     *
     * <code>uint64 created_at = 3;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }

    public static final int WEB_SITE_FIELD_NUMBER = 4;
    private volatile java.lang.Object webSite_;
    /**
     * <pre>
     * becomes webSite
     * </pre>
     *
     * <code>string web_site = 4;</code>
     */
    public java.lang.String getWebSite() {
      java.lang.Object ref = webSite_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        webSite_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * becomes webSite
     * </pre>
     *
     * <code>string web_site = 4;</code>
     */
    public com.google.protobuf.ByteString
        getWebSiteBytes() {
      java.lang.Object ref = webSite_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        webSite_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 5;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 5;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 6;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 7;
    private int version_;
    /**
     * <code>uint32 version = 7;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int PICTURE_FIELD_NUMBER = 8;
    private volatile java.lang.Object picture_;
    /**
     * <code>string picture = 8;</code>
     */
    public java.lang.String getPicture() {
      java.lang.Object ref = picture_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        picture_ = s;
        return s;
      }
    }
    /**
     * <code>string picture = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPictureBytes() {
      java.lang.Object ref = picture_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        picture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (updatedAt_ != 0L) {
        output.writeUInt64(2, updatedAt_);
      }
      if (createdAt_ != 0L) {
        output.writeUInt64(3, createdAt_);
      }
      if (!getWebSiteBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, webSite_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, description_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, name_);
      }
      if (version_ != 0) {
        output.writeUInt32(7, version_);
      }
      if (!getPictureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, picture_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (updatedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, updatedAt_);
      }
      if (createdAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, createdAt_);
      }
      if (!getWebSiteBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, webSite_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, description_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, name_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, version_);
      }
      if (!getPictureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, picture_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner)) {
        return super.equals(obj);
      }
      com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner other = (com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (getUpdatedAt()
          == other.getUpdatedAt());
      result = result && (getCreatedAt()
          == other.getCreatedAt());
      result = result && getWebSite()
          .equals(other.getWebSite());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && getName()
          .equals(other.getName());
      result = result && (getVersion()
          == other.getVersion());
      result = result && getPicture()
          .equals(other.getPicture());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdatedAt());
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreatedAt());
      hash = (37 * hash) + WEB_SITE_FIELD_NUMBER;
      hash = (53 * hash) + getWebSite().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + PICTURE_FIELD_NUMBER;
      hash = (53 * hash) + getPicture().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code partnerpackage.Partner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:partnerpackage.Partner)
        com.rcosteira.rabbitmq_protobufs_android.PartnerProto.PartnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rcosteira.rabbitmq_protobufs_android.PartnerProto.internal_static_partnerpackage_Partner_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rcosteira.rabbitmq_protobufs_android.PartnerProto.internal_static_partnerpackage_Partner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner.class, com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner.Builder.class);
      }

      // Construct using com.hidepixel.testsenincandroid.PartnerProto.Partner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        updatedAt_ = 0L;

        createdAt_ = 0L;

        webSite_ = "";

        description_ = "";

        name_ = "";

        version_ = 0;

        picture_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rcosteira.rabbitmq_protobufs_android.PartnerProto.internal_static_partnerpackage_Partner_descriptor;
      }

      public com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner getDefaultInstanceForType() {
        return com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner.getDefaultInstance();
      }

      public com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner build() {
        com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner buildPartial() {
        com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner result = new com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner(this);
        result.id_ = id_;
        result.updatedAt_ = updatedAt_;
        result.createdAt_ = createdAt_;
        result.webSite_ = webSite_;
        result.description_ = description_;
        result.name_ = name_;
        result.version_ = version_;
        result.picture_ = picture_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner) {
          return mergeFrom((com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner other) {
        if (other == com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getUpdatedAt() != 0L) {
          setUpdatedAt(other.getUpdatedAt());
        }
        if (other.getCreatedAt() != 0L) {
          setCreatedAt(other.getCreatedAt());
        }
        if (!other.getWebSite().isEmpty()) {
          webSite_ = other.webSite_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getPicture().isEmpty()) {
          picture_ = other.picture_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private long updatedAt_ ;
      /**
       * <pre>
       * becomes updatedAt
       * </pre>
       *
       * <code>uint64 updated_at = 2;</code>
       */
      public long getUpdatedAt() {
        return updatedAt_;
      }
      /**
       * <pre>
       * becomes updatedAt
       * </pre>
       *
       * <code>uint64 updated_at = 2;</code>
       */
      public Builder setUpdatedAt(long value) {
        
        updatedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * becomes updatedAt
       * </pre>
       *
       * <code>uint64 updated_at = 2;</code>
       */
      public Builder clearUpdatedAt() {
        
        updatedAt_ = 0L;
        onChanged();
        return this;
      }

      private long createdAt_ ;
      /**
       * <pre>
       * becomes createdAt
       * </pre>
       *
       * <code>uint64 created_at = 3;</code>
       */
      public long getCreatedAt() {
        return createdAt_;
      }
      /**
       * <pre>
       * becomes createdAt
       * </pre>
       *
       * <code>uint64 created_at = 3;</code>
       */
      public Builder setCreatedAt(long value) {
        
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * becomes createdAt
       * </pre>
       *
       * <code>uint64 created_at = 3;</code>
       */
      public Builder clearCreatedAt() {
        
        createdAt_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object webSite_ = "";
      /**
       * <pre>
       * becomes webSite
       * </pre>
       *
       * <code>string web_site = 4;</code>
       */
      public java.lang.String getWebSite() {
        java.lang.Object ref = webSite_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          webSite_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * becomes webSite
       * </pre>
       *
       * <code>string web_site = 4;</code>
       */
      public com.google.protobuf.ByteString
          getWebSiteBytes() {
        java.lang.Object ref = webSite_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          webSite_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * becomes webSite
       * </pre>
       *
       * <code>string web_site = 4;</code>
       */
      public Builder setWebSite(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        webSite_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * becomes webSite
       * </pre>
       *
       * <code>string web_site = 4;</code>
       */
      public Builder clearWebSite() {
        
        webSite_ = getDefaultInstance().getWebSite();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * becomes webSite
       * </pre>
       *
       * <code>string web_site = 4;</code>
       */
      public Builder setWebSiteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        webSite_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 5;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 5;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 5;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 5;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 6;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 6;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 6;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 6;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>uint32 version = 7;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>uint32 version = 7;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 version = 7;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object picture_ = "";
      /**
       * <code>string picture = 8;</code>
       */
      public java.lang.String getPicture() {
        java.lang.Object ref = picture_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          picture_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string picture = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPictureBytes() {
        java.lang.Object ref = picture_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          picture_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string picture = 8;</code>
       */
      public Builder setPicture(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        picture_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string picture = 8;</code>
       */
      public Builder clearPicture() {
        
        picture_ = getDefaultInstance().getPicture();
        onChanged();
        return this;
      }
      /**
       * <code>string picture = 8;</code>
       */
      public Builder setPictureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        picture_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:partnerpackage.Partner)
    }

    // @@protoc_insertion_point(class_scope:partnerpackage.Partner)
    private static final com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner();
    }

    public static com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Partner>
        PARSER = new com.google.protobuf.AbstractParser<Partner>() {
      public Partner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Partner(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Partner> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Partner> getParserForType() {
      return PARSER;
    }

    public com.rcosteira.rabbitmq_protobufs_android.PartnerProto.Partner getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_partnerpackage_Partner_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_partnerpackage_Partner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpartner.proto\022\016partnerpackage\"\224\001\n\007Part" +
      "ner\022\n\n\002id\030\001 \001(\t\022\022\n\nupdated_at\030\002 \001(\004\022\022\n\nc" +
      "reated_at\030\003 \001(\004\022\020\n\010web_site\030\004 \001(\t\022\023\n\013des" +
      "cription\030\005 \001(\t\022\014\n\004name\030\006 \001(\t\022\017\n\007version\030" +
      "\007 \001(\r\022\017\n\007picture\030\010 \001(\tB/\n\037com.hidepixel." +
      "testsenincandroidB\014PartnerProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_partnerpackage_Partner_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_partnerpackage_Partner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_partnerpackage_Partner_descriptor,
        new java.lang.String[] { "Id", "UpdatedAt", "CreatedAt", "WebSite", "Description", "Name", "Version", "Picture", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
